In [3]:
import numpy as np

In [4]:
x=2*np.random.rand(100,1)

In [5]:
x

array([[1.3230604 ],
       [0.90519163],
       [0.12579129],
       [0.39210589],
       [0.38671201],
       [1.89462268],
       [0.29807171],
       [1.17101611],
       [0.67144441],
       [0.19309402],
       [0.64433371],
       [0.0595141 ],
       [0.41154048],
       [1.38892181],
       [0.29077144],
       [1.11553087],
       [1.8490033 ],
       [0.79578179],
       [0.72450729],
       [1.45449577],
       [0.50046298],
       [1.76675329],
       [0.77309328],
       [1.54766811],
       [1.88075966],
       [0.85119495],
       [1.74018539],
       [1.67510697],
       [0.45998871],
       [0.93548585],
       [1.26420826],
       [1.02658318],
       [1.15667201],
       [0.43115294],
       [1.70714612],
       [1.4639908 ],
       [0.88527698],
       [1.09198571],
       [1.69086239],
       [0.12253076],
       [1.2322907 ],
       [1.31388721],
       [0.74735532],
       [1.52743414],
       [0.45594556],
       [1.81141073],
       [0.10611677],
       [0.983

In [7]:
y= 4 + 3 * x + np.random.randn(100, 1)

In [8]:
y

array([[ 6.50961339],
       [ 7.53548844],
       [ 3.96259512],
       [ 5.98274552],
       [ 4.13199443],
       [11.1192927 ],
       [ 7.69439332],
       [ 8.6892596 ],
       [ 5.29282438],
       [ 3.16795974],
       [ 4.95890334],
       [ 5.62086676],
       [ 4.97061002],
       [ 8.12440563],
       [ 3.68843704],
       [ 9.03727291],
       [ 9.51689321],
       [ 5.46553252],
       [ 6.84005547],
       [ 6.77347455],
       [ 5.99074371],
       [10.20822036],
       [ 5.83862943],
       [ 8.16636702],
       [10.30456911],
       [ 6.77999717],
       [10.58768978],
       [ 9.05082861],
       [ 5.24787644],
       [ 6.70407095],
       [ 5.99957404],
       [ 7.94895588],
       [ 8.5299504 ],
       [ 6.38138931],
       [ 9.28249209],
       [ 9.25499653],
       [ 7.29024263],
       [ 7.021027  ],
       [ 7.80610282],
       [ 5.3036517 ],
       [ 7.2114718 ],
       [ 8.55868139],
       [ 5.17745852],
       [ 7.59158276],
       [ 3.86719164],
       [ 7

In [10]:
x_b = np.c_[np.ones((100, 1)), x]

In [11]:
x_b

array([[1.        , 1.3230604 ],
       [1.        , 0.90519163],
       [1.        , 0.12579129],
       [1.        , 0.39210589],
       [1.        , 0.38671201],
       [1.        , 1.89462268],
       [1.        , 0.29807171],
       [1.        , 1.17101611],
       [1.        , 0.67144441],
       [1.        , 0.19309402],
       [1.        , 0.64433371],
       [1.        , 0.0595141 ],
       [1.        , 0.41154048],
       [1.        , 1.38892181],
       [1.        , 0.29077144],
       [1.        , 1.11553087],
       [1.        , 1.8490033 ],
       [1.        , 0.79578179],
       [1.        , 0.72450729],
       [1.        , 1.45449577],
       [1.        , 0.50046298],
       [1.        , 1.76675329],
       [1.        , 0.77309328],
       [1.        , 1.54766811],
       [1.        , 1.88075966],
       [1.        , 0.85119495],
       [1.        , 1.74018539],
       [1.        , 1.67510697],
       [1.        , 0.45998871],
       [1.        , 0.93548585],
       [1.

In [12]:
theta_best = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)

In [13]:
theta_best

array([[3.88479059],
       [3.12682678]])